In [1]:
import torch
from torchvision.transforms import v2

In [2]:
H, W = 32, 32
img = torch.randint(0, 256, size=(3, H, W), dtype=torch.uint8)

transforms = v2.Compose([
    v2.RandomResizedCrop(size=(224, 224), antialias=True),
    v2.RandomHorizontalFlip(p=0.5),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
img = transforms(img)
img

tensor([[[ 1.5125,  1.5125,  1.5125,  ...,  0.8104,  0.8104,  0.8104],
         [ 1.5125,  1.5125,  1.5125,  ...,  0.8104,  0.8104,  0.8104],
         [ 1.5125,  1.5125,  1.5125,  ...,  0.8104,  0.8104,  0.8104],
         ...,
         [-0.0116, -0.0116, -0.0116,  ..., -1.0219, -1.0219, -1.0219],
         [-0.0116, -0.0116, -0.0116,  ..., -1.0219, -1.0219, -1.0219],
         [-0.0116, -0.0116, -0.0116,  ..., -1.0219, -1.0219, -1.0219]],

        [[ 2.4286,  2.4286,  2.4286,  ...,  1.1331,  1.1331,  1.1331],
         [ 2.4286,  2.4286,  2.4286,  ...,  1.1331,  1.1331,  1.1331],
         [ 2.4286,  2.4286,  2.4286,  ...,  1.1331,  1.1331,  1.1331],
         ...,
         [-0.3901, -0.3901, -0.3901,  ...,  1.7808,  1.7808,  1.7808],
         [-0.3901, -0.3901, -0.3901,  ...,  1.7808,  1.7808,  1.7808],
         [-0.3901, -0.3901, -0.3901,  ...,  1.7808,  1.7808,  1.7808]],

        [[-1.5081, -1.5081, -1.5081,  ..., -0.7238, -0.7238, -0.7238],
         [-1.5081, -1.5081, -1.5081,  ..., -0

In [3]:
from torchvision import tv_tensors

img = torch.randint(0, 256, size=(3, H, W), dtype=torch.uint8)
boxes = torch.randint(0, H//2, size=(3, 4))
boxes[:, 2:] += boxes[:, :2]
boxes = tv_tensors.BoundingBoxes(boxes, format="XYXY", canvas_size=(H, W))

img, boxes = transforms(img, boxes)
output_dict = transforms({"image": img, "boxes": boxes})

In [18]:
a = torch.tensor([1, 2, 3.])
b = torch.tensor([3, 2, 1.])
print(a.repeat((3, 2)).reshape((3, 2, 3)) / b[:, None, None])
print(a[:, None, None].repeat_interleave(6).reshape((3, 2, 3)))

tensor([[[0.3333, 0.6667, 1.0000],
         [0.3333, 0.6667, 1.0000]],

        [[0.5000, 1.0000, 1.5000],
         [0.5000, 1.0000, 1.5000]],

        [[1.0000, 2.0000, 3.0000],
         [1.0000, 2.0000, 3.0000]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [3., 3., 3.]]])


In [49]:
torch.empty(1).uniform_(0., float(len(a))).item()

2.4931271076202393

In [58]:
# timages = torch.normal(0, 1, size=(2, 3, 800, 1120))
images = torch.normal(0, 1, size=(3, 800, 1088))
images = [images] * 2

bts = images[0].new_full([2, 3, 800, 1120], 0)
print(bts)

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
        