In [1]:
import torch
from torch import nn

### 测试BatchNorm2d用法

In [2]:
x1 = torch.tensor([[[1, 1], [1, 2]], [[-1, 1], [0, 1]]], dtype=torch.float32)
x2 = torch.tensor([[[0, -1], [2, 2]], [[0, -1], [3, 1]]], dtype=torch.float32)
print(f'{x1}\n{x2}')
print(x1.shape)

tensor([[[ 1.,  1.],
         [ 1.,  2.]],

        [[-1.,  1.],
         [ 0.,  1.]]])
tensor([[[ 0., -1.],
         [ 2.,  2.]],

        [[ 0., -1.],
         [ 3.,  1.]]])
torch.Size([2, 2, 2])


In [3]:
x = torch.cat((x1.unsqueeze(0), x2.unsqueeze(0)), dim=0)
print(f'{x}\n{x.shape}')

tensor([[[[ 1.,  1.],
          [ 1.,  2.]],

         [[-1.,  1.],
          [ 0.,  1.]]],


        [[[ 0., -1.],
          [ 2.,  2.]],

         [[ 0., -1.],
          [ 3.,  1.]]]])
torch.Size([2, 2, 2, 2])


In [4]:
f = nn.BatchNorm2d(2)
f(x)

tensor([[[[ 0.0000,  0.0000],
          [ 0.0000,  1.0000]],

         [[-1.2247,  0.4082],
          [-0.4082,  0.4082]]],


        [[[-1.0000, -2.0000],
          [ 1.0000,  1.0000]],

         [[-0.4082, -1.2247],
          [ 2.0412,  0.4082]]]], grad_fn=<NativeBatchNormBackward0>)

### 交叉熵损失

In [7]:
x = torch.randn(3, 5)
print(f'x = {x}')
label = torch.tensor([1, 0, 3])
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(x, label)
print(loss)

x = tensor([[ 1.8750,  0.5672, -0.9249, -0.3654,  1.0278],
        [ 0.8115,  1.2725,  0.2274, -0.3150,  0.5493],
        [ 0.0243, -0.3601,  0.1398, -0.6998,  0.8926]])
tensor(1.9450)


In [14]:
softmax = nn.Softmax()
p1 = softmax(x)
print(f'p1 = {p1}')
print(f'sum = {torch.sum(p1, dim=1, keepdim=True)}')

p1 = tensor([[0.5358, 0.1449, 0.0326, 0.0570, 0.2297],
        [0.2360, 0.3743, 0.1316, 0.0765, 0.1816],
        [0.1763, 0.1201, 0.1979, 0.0855, 0.4202]])
sum = tensor([[1.0000],
        [1.0000],
        [1.0000]])


/tmp/ipykernel_94831/3089901900.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  p1 = softmax(x)


### 生成vgg16网络

In [15]:
from torchvision import models

In [17]:
vgg16 = models.vgg16()
torch.save(vgg16, "../data_set/vgg16.pth")